services:
  - type: web
    name: neuroguard-api
    env: docker
    region: frankfurt
    plan: free
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true

  - type: static
    name: neuroguard-frontend
    env: static
    buildCommand: npm install && npm run build
    publishPath: ./frontend/dist
    rootDir: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index2.html


